/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrandPi.gui;

import TrandPi.dao.UserDAO;
import TrandPi.dao.participantDAO;
import TrandPi.pojo.CurrentUser;
import TrandPi.pojo.participantPojo;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ptEditProfileFrame extends javax.swing.JFrame {
    private File file;
    private String oldpwd,npwd,cnfpwd;
    /**
     * Creates new form ptEditProfileFrame
     */
    public ptEditProfileFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        pwdPanel.setVisible(false);
        resumePanel.setVisible(false);
        loadData();
    }
    private void loadData()
    {
        try{
            participantPojo pt=participantDAO.getParticipantbyId(CurrentUser.getId());
            lblname.setText(pt.getName());
            lblmail.setText(pt.getUserId());
            lblphone.setText(pt.getPhone());
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Db error in edit profile", "Error!!", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboxresumepanel = new javax.swing.JCheckBox();
        btnsave = new javax.swing.JButton();
        resumePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnbrowse = new javax.swing.JButton();
        txtfilepath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboxpwdpanel = new javax.swing.JCheckBox();
        pwdPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtoldpwd = new javax.swing.JPasswordField();
        txtnewpwd = new javax.swing.JPasswordField();
        txtcnfpwd = new javax.swing.JPasswordField();
        btndiscard = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(243, 246, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\TrandPi\\src\\TrandPi\\gui\\transparent logo.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\TrandPi\\src\\TrandPi\\gui\\World-Map.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name:-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone No:-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("mail Address:-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Want to change resume");

        cboxresumepanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxresumepanelActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText("Save changes");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        resumePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("upload resume within 1000kb");

        btnbrowse.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnbrowse.setText("Browse File");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        txtfilepath.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout resumePanelLayout = new javax.swing.GroupLayout(resumePanel);
        resumePanel.setLayout(resumePanelLayout);
        resumePanelLayout.setHorizontalGroup(
            resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumePanelLayout.createSequentialGroup()
                .addComponent(txtfilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbrowse))
            .addComponent(jLabel7)
        );
        resumePanelLayout.setVerticalGroup(
            resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumePanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addGroup(resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbrowse))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Wants to change password");

        cboxpwdpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxpwdpanelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Confirm new Password");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("New Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Current Password");

        txtoldpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtnewpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtcnfpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout pwdPanelLayout = new javax.swing.GroupLayout(pwdPanel);
        pwdPanel.setLayout(pwdPanelLayout);
        pwdPanelLayout.setHorizontalGroup(
            pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwdPanelLayout.createSequentialGroup()
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcnfpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(txtnewpwd)
                    .addComponent(txtoldpwd))
                .addContainerGap())
        );
        pwdPanelLayout.setVerticalGroup(
            pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwdPanelLayout.createSequentialGroup()
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtoldpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnewpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcnfpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btndiscard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndiscard.setText("Discard Changes");
        btndiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiscardActionPerformed(evt);
            }
        });

        lblname.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        lblphone.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        lblmail.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btndiscard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxpwdpanel))
                                    .addComponent(pwdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboxresumepanel))
                                    .addComponent(resumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3))
                            .addComponent(cboxpwdpanel))
                        .addGap(23, 23, 23)
                        .addComponent(pwdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cboxresumepanel))
                .addComponent(resumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndiscard, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxpwdpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxpwdpanelActionPerformed
        if (cboxpwdpanel.isSelected()) {
              pwdPanel.setVisible(true);
        }
        else{
            pwdPanel.setVisible(false);
        }
    }//GEN-LAST:event_cboxpwdpanelActionPerformed
     private boolean validateInput()
    {
        char []arroldpwd=txtoldpwd.getPassword();
        char []arrnpwd=txtnewpwd.getPassword();
        char []arrcnfrmpwd=txtcnfpwd.getPassword();
        if (arroldpwd.length==0||arrnpwd.length==0||arrcnfrmpwd.length==0) {
            return false;
        }
        oldpwd=String.valueOf(arroldpwd);
        npwd=String.valueOf(arrnpwd);
        cnfpwd=String.valueOf(arrcnfrmpwd);
        return true;
    }
     private boolean matchPwd()
     {
         return npwd.equals(cnfpwd);
     }
    private void cboxresumepanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxresumepanelActionPerformed
       if (cboxresumepanel.isSelected()) {
              resumePanel.setVisible(true);
        }
        else{
            resumePanel.setVisible(false);
        }
    }//GEN-LAST:event_cboxresumepanelActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        JFileChooser filechooser=new JFileChooser();
        filechooser.setDialogTitle("Select your resume");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result=filechooser.showOpenDialog(null);
        if (result==JFileChooser.APPROVE_OPTION) {
            file=filechooser.getSelectedFile();
            txtfilepath.setText(file.getAbsolutePath()); 
        }
    }//GEN-LAST:event_btnbrowseActionPerformed

    

    private void btndiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiscardActionPerformed
       new participantsOptionFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btndiscardActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       boolean pwdchanged=false,resumeUpdated=false;
        if (cboxpwdpanel.isSelected()) {
            if (validateInput()==false) {
                JOptionPane.showMessageDialog(null,"Plzz fill all the fields","Empty fields",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (matchPwd()==false) {
                JOptionPane.showMessageDialog(null,"Password and confirm password do not match","password missmatch",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
               
                boolean resp=UserDAO.checkOldPassword(CurrentUser.getId(),oldpwd);
                if(resp==true){
                    UserDAO.updateParticipantPassword(CurrentUser.getId(), npwd);
                    pwdchanged=true;
                }else{
                   JOptionPane.showMessageDialog(null, "Your Old Password Is Wrong!","Password Mismatching",JOptionPane.WARNING_MESSAGE);
               }
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }      
        }  
        if(cboxresumepanel.isSelected()){
            if(txtfilepath.getText().trim()!=""){
                
            try{
                participantDAO.updateResume(CurrentUser.getId(), file);
                resumeUpdated=true;      
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }
            catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null,"File Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }
         }
        }
        if(pwdchanged && resumeUpdated){
          JOptionPane.showMessageDialog(null, "Password & Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
      else if(pwdchanged){
          JOptionPane.showMessageDialog(null, "Password Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
      else if(resumeUpdated){
          JOptionPane.showMessageDialog(null, "Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
      else{
          JOptionPane.showMessageDialog(null, "No Changes Done!!","Message!",JOptionPane.INFORMATION_MESSAGE);
        }
                 
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ptEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ptEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ptEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ptEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ptEditProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btndiscard;
    private javax.swing.JButton btnsave;
    private javax.swing.JCheckBox cboxpwdpanel;
    private javax.swing.JCheckBox cboxresumepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel pwdPanel;
    private javax.swing.JPanel resumePanel;
    private javax.swing.JPasswordField txtcnfpwd;
    private javax.swing.JTextField txtfilepath;
    private javax.swing.JPasswordField txtnewpwd;
    private javax.swing.JPasswordField txtoldpwd;
    // End of variables declaration//GEN-END:variables
}
